import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Pridi } from 'next/font/google';
import { WeatherProvider } from '@/context/WeatherContext';
import HeaderBar from '@/components/HeaderBar/HeaderBar';
import Navbar from '@/components/Navbar/Navbar';
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const pridi = Pridi({
  subsets: ['latin'],
  weight: '400',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pridi.className} antialiased`}>
        <main className="flex  bg-blue-200 min-h-screen  ">
          <div className="mx-auto container justify-center">
            <WeatherProvider>
              <HeaderBar />
              <Navbar />
              {children}
            </WeatherProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
